export const WHATSAPP_NUMBER = "237672203290";
export const INSTAGRAM = "https://www.instagram.com/ws_fragrances";
export const TIKTOK = "https://www.tiktok.com/@ws_frangrances?_r=1&_t=ZG-96xKox84ruy";

export const NOTES = ["Oud", "Rose", "Musk", "Amber", "Vanilla", "Sandalwood", "Bergamot", "Jasmine", "Citrus", "Tobacco", "Patchouli", "Lavender"];

export const CATEGORIES_EN = [
  { id: "all", label: "All" },
  { id: "men", label: "For Him" },
  { id: "women", label: "For Her" },
  { id: "unisex", label: "Unisex" },
  { id: "oud", label: "Oud" },
  { id: "fresh", label: "Fresh" },
  { id: "oriental", label: "Oriental" },
];
export const CATEGORIES_FR = [
  { id: "all", label: "Tous" },
  { id: "men", label: "Pour Lui" },
  { id: "women", label: "Pour Elle" },
  { id: "unisex", label: "Unisexe" },
  { id: "oud", label: "Oud" },
  { id: "fresh", label: "Frais" },
  { id: "oriental", label: "Oriental" },
];

export const BRANDS = ["All", "Lattafa", "Afnan", "French Avenue", "Paris Corner", "Armaf", "Maison Alhambra", "Fragrance World"];
export const BRANDS_FR = ["Tous", "Lattafa", "Afnan", "French Avenue", "Paris Corner", "Armaf", "Maison Alhambra", "Fragrance World"];

export const PERFUMES = [
  // ── LATTAFA ──────────────────────────────────────────
  {
    id: 1, name: "Oud For Glory", brand: "Lattafa", category: "unisex",
    price: 25000, originalPrice: 30000,
    notes: ["Oud", "Rose", "Musk", "Amber"],
    descEn: "A majestic oud fragrance that opens with rich agarwood, blooms into velvety rose, and settles into a warm amber and musk base. Deeply luxurious and long-lasting.",
    descFr: "Une majestueuse fragrance oud qui s'ouvre sur un bois d'agar riche, s'épanouit en rose veloutée et se fixe sur une base d'ambre et de musc. Profondément luxueux.",
    size: "100ml EDP", rating: 4.9, reviews: 47, badge: "Best Seller",
    hue: "#8B4513", accent: "#C9A84C",
    image: "/lattafa-bade-e-al-oud-edp-100ml-removebg-preview.png",
  },
  {
    id: 2, name: "Asad", brand: "Lattafa", category: "men",
    price: 25000, originalPrice: null,
    notes: ["Amber", "Tobacco", "Musk", "Vanilla"],
    descEn: "Bold and commanding. Asad opens with smoky tobacco layered over warm amber and rich musk, drying down into a creamy vanilla base. A true statement scent for men.",
    descFr: "Audacieux et dominant. Asad s'ouvre sur un tabac fumé sur fond d'ambre chaud, se fixant sur une base crémeuse de vanille. Une fragrance masculine affirmée.",
    size: "100ml EDP", rating: 4.8, reviews: 63, badge: "New",
    hue: "#3D1C00", accent: "#A0522D",
    image: "/asad-removebg-preview.png",
  },
  {
    id: 3, name: "Yara", brand: "Lattafa", category: "women",
    price: 20000, originalPrice: 25000,
    notes: ["Jasmine", "Rose", "Vanilla", "Musk"],
    descEn: "Yara is a delicate floral bouquet opening with jasmine and rose, heart warming into vanilla and settling into soft musk. Feminine, soft and irresistibly elegant.",
    descFr: "Yara est un délicat bouquet floral de jasmin et de rose, se réchauffant en vanille et se fixant dans un musc doux. Féminin, doux et irrésistiblement élégant.",
    size: "100ml EDP", rating: 4.7, reviews: 38, badge: "Best Seller",
    hue: "#6B0040", accent: "#D4578C",
    image: "/719ciAA2OBL._AC_UF1000_1000_QL80_-removebg-preview.png",
  },
  {
    id: 9, name: "Yara Moi", brand: "Lattafa", category: "women",
    price: 12500, originalPrice: null,
    notes: ["Jasmine", "Citrus", "Vanilla", "Musk"],
    descEn: "Sun-drenched and joyful. Yara Moi opens with radiant jasmine and fresh citrus, blossoming into a warm vanilla and soft musk base. Light, sensual and captivating.",
    descFr: "Ensoleillée et joyeuse. Yara Moi s'ouvre sur un jasmin rayonnant et des agrumes frais, s'épanouissant sur une base de vanille chaude et de musc doux.",
    size: "100ml EDP", rating: 4.4, reviews: 19, badge: null,
    hue: "#5C3A00", accent: "#E8A020",
    image: "/yaramoiaceite_grande-removebg-preview.png",
  },
  {
    id: 16, name: "Yara Candy", brand: "Lattafa", category: "women",
    price: 20000, originalPrice: null,
    notes: ["Rose", "Jasmine", "Vanilla", "Musk"],
    descEn: "Playful and sweet. Yara Candy bursts with rose and jasmine at the top, melting into a rich vanilla and musk base. Glamorous, feminine and utterly irresistible.",
    descFr: "Joueur et sucré. Yara Candy éclate de rose et de jasmin en tête, fondant dans une base de vanille riche et de musc. Glamour, féminin et irrésistible.",
    size: "100ml EDP", rating: 4.8, reviews: 52, badge: "New",
    hue: "#3D0028", accent: "#E880CC",
    image: "/yara_candy-removebg-preview.png",
  },

  // ── AFNAN ──────────────────────────────────────────
  {
    id: 5, name: "9PM", brand: "Afnan", category: "men",
    price: 25000, originalPrice: null,
    notes: ["Bergamot", "Amber", "Vanilla", "Musk"],
    descEn: "Inspired by Paco Rabanne Invictus. A fresh bergamot and citrus opening descends into a warm, sensual amber and vanilla drydown. Nuclear sillage, perfect for evenings.",
    descFr: "Inspiré de Paco Rabanne Invictus. Une ouverture bergamote et agrumes descend vers un fond d'ambre chaud et de vanille sensuelle. Parfait pour les soirées.",
    size: "100ml EDP", rating: 4.9, reviews: 82, badge: "Top Pick",
    hue: "#0A0A2E", accent: "#4444CC",
    image: "/9pm-removebg-preview.png",
  },
  {
    id: 6, name: "9PM Elixir", brand: "Afnan", category: "men",
    price: 30000, originalPrice: 35000,
    notes: ["Bergamot", "Lavender", "Sandalwood", "Vanilla"],
    descEn: "The elevated version of 9PM. Opens with bergamot and lavender, transitioning into a rich sandalwood and creamy vanilla base. Sophisticated, powerful and long-lasting.",
    descFr: "La version premium de 9PM. S'ouvre sur bergamote et lavande, vers un santal riche et une base crémeuse de vanille. Sophistiqué, puissant et durable.",
    size: "100ml EDP", rating: 4.6, reviews: 55, badge: null,
    hue: "#2A2A2A", accent: "#A0A0A0",
    image: "/9pm_elixir-removebg-preview.png",
  },
  {
    id: 13, name: "9PM Night Out", brand: "Afnan", category: "men",
    price: 40000, originalPrice: 50000,
    notes: ["Bergamot", "Lavender", "Sandalwood", "Vanilla"],
    descEn: "The most intense expression in the 9PM family. A bold, powerful oriental fragrance designed for special evenings. Lavender and bergamot over sandalwood and tonka.",
    descFr: "L'expression la plus intense de la famille 9PM. Une fragrance orientale puissante pour les soirées spéciales. Lavande et bergamote sur santal et tonka.",
    size: "100ml EDP", rating: 4.7, reviews: 44, badge: "Sale",
    hue: "#0A001A", accent: "#6600CC",
    image: "/9pm_nightout-removebg-preview.png",
  },

  // ── FRENCH AVENUE ──────────────────────────────────
  {
    id: 4, name: "Vulcan Feu", brand: "French Avenue", category: "unisex",
    price: 30000, originalPrice: 35000,
    notes: ["Oud", "Patchouli", "Tobacco", "Musk"],
    descEn: "Dark and volcanic. Vulcan Feu ignites with smoky oud and deep patchouli layered over tobacco and musk. A fiery, resinous masterpiece for those who dare.",
    descFr: "Sombre et volcanique. Vulcan Feu s'enflamme avec un oud fumé et un patchouli profond sur fond de tabac et de musc. Un chef-d'œuvre résineux pour les audacieux.",
    size: "100ml EDP", rating: 5.0, reviews: 29, badge: "Premium",
    hue: "#1A0A2E", accent: "#7B5EA7",
    image: "/vulcan_feu-removebg-preview.png",
  },
  {
    id: 8, name: "Amber D'or", brand: "French Avenue", category: "unisex",
    price: 25000, originalPrice: 29000,
    notes: ["Amber", "Rose", "Oud", "Musk"],
    descEn: "An opulent golden fragrance. Amber D'or blends warm golden amber with rich oud and soft rose, settling into a sensual musk base. Your personal seal of luxury.",
    descFr: "Une fragrance dorée et opulente. Amber D'or mêle ambre doré et chaud avec oud riche et rose douce, sur un fond de musc sensuel. Votre sceau personnel de luxe.",
    size: "100ml EDP", rating: 4.7, reviews: 31, badge: "Sale",
    hue: "#4A3200", accent: "#C9A84C",
    image: "/french-avenue-amber-d-or-edp-100ml-removebg-preview.png",
  },
  {
    id: 10, name: "Liquid Brun", brand: "French Avenue", category: "men",
    price: 35000, originalPrice: 40000,
    notes: ["Tobacco", "Oud", "Amber", "Sandalwood"],
    descEn: "Bold and unwavering. Liquid Brun opens with rich tobacco leaf and oud resin, deepening into warm sandalwood and amber. A commanding, sophisticated presence.",
    descFr: "Audacieux et déterminé. Liquid Brun s'ouvre sur une feuille de tabac riche et une résine d'oud, se renforçant sur santal chaud et ambre. Une présence imposante.",
    size: "100ml EDP", rating: 4.8, reviews: 41, badge: "Best Seller",
    hue: "#1E0A00", accent: "#7B3A00",
    image: "/liquid_brun-removebg-preview.png",
  },
  {
    id: 11, name: "Vulcan Sable", brand: "French Avenue", category: "men",
    price: 35000, originalPrice: 40000,
    notes: ["Bergamot", "Jasmine", "Amber", "Vanilla"],
    descEn: "The refined desert wind. Vulcan Sable opens bright with bergamot, reveals a floral jasmine heart, and settles into a warm amber and vanilla drydown of pure luxury.",
    descFr: "Le vent du désert raffiné. Vulcan Sable s'ouvre brillamment sur bergamote, révèle un cœur floral de jasmin et se fixe en ambre chaud et vanille.",
    size: "100ml EDP", rating: 4.9, reviews: 58, badge: "Premium",
    hue: "#2A2A00", accent: "#C8A800",
    image: "/vulcan_sable-removebg-preview.png",
  },
  {
    id: 15, name: "Aoud Azzure", brand: "French Avenue", category: "unisex",
    price: 30000, originalPrice: 38000,
    notes: ["Oud", "Rose", "Sandalwood", "Amber"],
    descEn: "A royal azure oud composition. Opens with spiced rose and precious oud, deepening into creamy sandalwood and a warm amber base. Pure Middle Eastern luxury.",
    descFr: "Une composition royale d'oud azuré. S'ouvre sur rose épicée et oud précieux, se renforçant sur santal crémeux et base d'ambre chaude. Luxe pur du Moyen-Orient.",
    size: "100ml EDP", rating: 5.0, reviews: 35, badge: "Luxury",
    hue: "#2A1000", accent: "#9B6910",
    image: "/Aoud_azurre-removebg-preview.png",
  },

  // ── PARIS CORNER ───────────────────────────────────
  {
    id: 7, name: "Marshmallow Blush", brand: "Paris Corner", category: "women",
    price: 35000, originalPrice: null,
    notes: ["Rose", "Jasmine", "Bergamot", "Sandalwood"],
    descEn: "Soft and dreamy. Marshmallow Blush opens with bergamot and jasmine, blooming into a lush rose heart, softly wrapped in creamy sandalwood. Delicate femininity.",
    descFr: "Doux et rêveur. Marshmallow Blush s'ouvre sur bergamote et jasmin, s'épanouissant en rose luxuriante enveloppée de santal crémeux. Féminité délicate.",
    size: "100ml EDP", rating: 4.5, reviews: 24, badge: null,
    hue: "#5C0030", accent: "#E87AAB",
    image: "/marshmallow_blush-removebg-preview.png",
  },
  {
    id: 14, name: "Rifaaqat", brand: "Paris Corner", category: "unisex",
    price: 25000, originalPrice: null,
    notes: ["Rose", "Oud", "Musk", "Amber"],
    descEn: "Rifaaqat means 'companionship' in Arabic. Rose and oud intertwine with warm amber and soft musk, creating a deeply personal and intimate fragrance you'll never forget.",
    descFr: "Rifaaqat signifie 'compagnonnage' en arabe. Rose et oud s'entrelacent avec ambre chaud et musc doux, créant une fragrance profondément personnelle et intime.",
    size: "100ml EDP", rating: 4.6, reviews: 27, badge: null,
    hue: "#3D0020", accent: "#CC006B",
    image: "/rifaqaat-removebg-preview.png",
  },

  // ── ARMAF ──────────────────────────────────────────
  {
    id: 12, name: "Club De Nuit Intense Man", brand: "Armaf", category: "men",
    price: 30000, originalPrice: null,
    notes: ["Bergamot", "Patchouli", "Amber", "Musk"],
    descEn: "Inspired by Creed Aventus. Opens with fresh bergamot and birch, transitions into patchouli and jasmine, settling into a powerful amber and musk base. Iconic and timeless.",
    descFr: "Inspiré de Creed Aventus. S'ouvre sur bergamote fraîche et bouleau, vers patchouli et jasmin, sur une base puissante d'ambre et musc. Iconique et intemporel.",
    size: "105ml EDP", rating: 5.0, reviews: 96, badge: "Iconic",
    hue: "#00001A", accent: "#3366CC",
    image: "/club_de_nuit_intense-removebg-preview.png",
  },

  // ── FRAGRANCE WORLD ────────────────────────────────
  {
    id: 17, name: "Valiance L'Origine", brand: "Fragrance World", category: "unisex",
    price: 18000, originalPrice: null,
    notes: ["Oud", "Bergamot", "Amber", "Sandalwood"],
    descEn: "Inspired by Gucci Intense Oud. Opens with bergamot and lemon over a smoky oud and incense heart, drying down to guaiac wood and tonka bean. Intense, regal and complex.",
    descFr: "Inspiré de Gucci Intense Oud. S'ouvre sur bergamote et citron, sur un cœur d'oud fumé et d'encens, se fixant sur bois de gaïac et fève tonka. Intense et royal.",
    size: "100ml EDP", rating: 4.7, reviews: 31, badge: null,
    hue: "#1A0800", accent: "#8B6914",
    image: "/valiance.png",
  },
  {
    id: 18, name: "Fiero Blue Man", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Bergamot", "Lavender", "Sandalwood", "Musk"],
    descEn: "A bold masculine fragrance. Opens with bergamot and pepper, transitions into lavender and cardamom, settling into a woody base of ambroxan and cedarwood. Confident and modern.",
    descFr: "Une fragrance masculine audacieuse. S'ouvre sur bergamote et poivre, vers lavande et cardamome, se fixant sur ambroxan et cèdre. Confiant et moderne.",
    size: "100ml EDP", rating: 4.6, reviews: 24, badge: null,
    hue: "#001A3D", accent: "#3399FF",
    image: "/fiero.png",
  },
  {
    id: 19, name: "Extremely Unique", brand: "Fragrance World", category: "unisex",
    price: 18000, originalPrice: null,
    notes: ["Citrus", "Jasmine", "Musk", "Sandalwood"],
    descEn: "A vibrant unisex fragrance. Orange, watermelon and blueberry burst at the top, melting into a tropical jasmine and tiare heart, settling into ambroxan, musk and sandalwood.",
    descFr: "Une fragrance unisexe vibrante. Orange, pastèque et myrtille éclatent en tête, fondant dans un cœur tropical de jasmin et tiaré, sur fond d'ambroxan, musc et santal.",
    size: "100ml EDP", rating: 4.5, reviews: 18, badge: null,
    hue: "#003D1A", accent: "#00CC66",
    image: null,
  },
  {
    id: 20, name: "Proud of You", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Vanilla", "Amber", "Musk", "Sandalwood"],
    descEn: "Inspired by Armani Stronger With You. Opens with bergamot and rum, transitions into lavender and davana, settling into chestnut, vanilla and patchouli. Warm, sweet and masculine.",
    descFr: "Inspiré d'Armani Stronger With You. S'ouvre sur bergamote et rhum, vers lavande et davana, se fixant sur châtaigne, vanille et patchouli. Chaud, doux et masculin.",
    size: "100ml EDP", rating: 4.7, reviews: 42, badge: null,
    hue: "#2A1A00", accent: "#CC8800",
    image: "/proud_of_you_tobacco.png",
  },
  {
    id: 21, name: "Proud of You Intense", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Bergamot", "Lavender", "Amber", "Vanilla"],
    descEn: "Inspired by Armani Stronger With You Intensely. Opens with pepper, bergamot and cardamom, heart of cinnamon, sage and lavender, base of vanilla, tonka, amber and musk.",
    descFr: "Inspiré d'Armani Stronger With You Intensely. S'ouvre sur poivre, bergamote et cardamome, cœur de cannelle, sauge et lavande, base de vanille, tonka et ambre.",
    size: "100ml EDP", rating: 4.8, reviews: 37, badge: "New",
    hue: "#1A0A00", accent: "#CC6600",
    image: "/proud_of_you_intense.png",
  },
  {
    id: 22, name: "Proud of You Amber", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Amber", "Vanilla", "Lavender", "Musk"],
    descEn: "Inspired by Armani Stronger With You Amber. Cardamom, pepper and bergamot open this warm oriental, transitioning into lavender, cinnamon and sage, closing on vanilla, tonka and woody amber.",
    descFr: "Inspiré d'Armani Stronger With You Amber. Cardamome, poivre et bergamote ouvrent cet oriental chaud, vers lavande, cannelle et sauge, se fermant sur vanille, tonka et ambre boisé.",
    size: "100ml EDP", rating: 4.7, reviews: 29, badge: null,
    hue: "#3D1A00", accent: "#DD9900",
    image: "/proud_of_you_amber.png",
  },
  {
    id: 23, name: "Invicto Elixir", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Lavender", "Patchouli", "Vanilla", "Amber"],
    descEn: "Inspired by Paco Rabanne Invictus Victory Elixir. Opens with lavender, cardamom and black pepper, heart of incense and patchouli, base of vanilla pod and tonka bean. Powerful and victorious.",
    descFr: "Inspiré de Paco Rabanne Invictus Victory Elixir. S'ouvre sur lavande, cardamome et poivre noir, cœur d'encens et patchouli, base de vanille et fève tonka. Puissant et victorieux.",
    size: "100ml EDP", rating: 4.8, reviews: 51, badge: "Top Pick",
    hue: "#003322", accent: "#00AA77",
    image: "/invicto2.png",
  },
  {
    id: 24, name: "Invicto Intense", brand: "Fragrance World", category: "men",
    price: 18000, originalPrice: null,
    notes: ["Amber", "Musk", "Citrus", "Sandalwood"],
    descEn: "Inspired by Paco Rabanne Invictus Intense. Orange blossom and black pepper open this masculine powerhouse, transitioning into whiskey and bay leaf, closing on salt, ambergris and amber.",
    descFr: "Inspiré de Paco Rabanne Invictus Intense. Fleur d'oranger et poivre noir ouvrent ce parfum masculin, vers whiskey et laurier, se fermant sur sel, ambre gris et ambre.",
    size: "100ml EDP", rating: 4.6, reviews: 33, badge: null,
    hue: "#0A0020", accent: "#5500CC",
    image: "/invicto1.png",
  },
  {
    id: 25, name: "Oud Nuclear", brand: "Fragrance World", category: "unisex",
    price: 20000, originalPrice: null,
    notes: ["Oud", "Rose", "Patchouli", "Amber"],
    descEn: "Inspired by Maison Crivelli Oud Stallion. Opens with saffron, cardamom and nutmeg, heart of osmanthus, jasmine and Turkish rose, base of agarwood, leather, cedar, tonka and patchouli.",
    descFr: "Inspiré de Maison Crivelli Oud Stallion. S'ouvre sur safran, cardamome et noix de muscade, cœur d'osmanthus, jasmin et rose turque, base d'agarwood, cuir, cèdre et tonka.",
    size: "60ml EDP", rating: 4.9, reviews: 28, badge: "Luxury",
    hue: "#1A0500", accent: "#AA4400",
    image: "/oud_nuclear.png",
  },
  {
    id: 26, name: "Oud Stallion", brand: "Fragrance World", category: "unisex",
    price: 20000, originalPrice: null,
    notes: ["Oud", "Rose", "Sandalwood", "Patchouli"],
    descEn: "A bold oriental-woody fragrance. Saffron and cardamom ignite the opening, a rose and osmanthus heart adds opulent florality, while oud, leather and patchouli create an unforgettable dark base.",
    descFr: "Une fragrance orientale-boisée audacieuse. Safran et cardamome enflamment l'ouverture, un cœur de rose et osmanthus, tandis qu'oud, cuir et patchouli créent une base sombre inoubliable.",
    size: "100ml EDP", rating: 4.8, reviews: 22, badge: "Premium",
    hue: "#2A0A00", accent: "#993300",
    image: "oud_stallion.png",
  },
  {
    id: 27, name: "Cocktail Intense", brand: "Fragrance World", category: "unisex",
    price: 18000, originalPrice: null,
    notes: ["Tobacco", "Vanilla", "Amber", "Musk"],
    descEn: "Inspired by Kilian Angels' Share. Opens with cognac, cinnamon and plum, transitions into myrrh and iris, settling into a rich vanilla, tonka and sandalwood base. Boozy, warm and unforgettable.",
    descFr: "Inspiré de Kilian Angels' Share. S'ouvre sur cognac, cannelle et prune, vers myrrhe et iris, se fixant sur vanille riche, tonka et santal. Alcoolisé, chaud et inoubliable.",
    size: "100ml EDP", rating: 4.8, reviews: 64, badge: "Best Seller",
    hue: "#3D1500", accent: "#CC5500",
    image: "cocktail_intense.png",
  },
  {
    id: 28, name: "Vanilla So Sweet", brand: "Fragrance World", category: "unisex",
    price: 18000, originalPrice: null,
    notes: ["Vanilla", "Rose", "Jasmine", "Amber"],
    descEn: "Inspired by Guerlain Spiritueuse Double Vanille. Opens with pink pepper, bergamot and incense, blooms into ylang-ylang, jasmine and rose, closing on a rich vanilla, rum and benzoin base.",
    descFr: "Inspiré de Guerlain Spiritueuse Double Vanille. S'ouvre sur poivre rose, bergamote et encens, s'épanouit en ylang-ylang, jasmin et rose, sur une riche base de vanille, rhum et benjoin.",
    size: "100ml EDP", rating: 4.7, reviews: 39, badge: null,
    hue: "#2A0020", accent: "#CC4499",
    image: "/vanilla_so_sweet.png",
  },
  {
    id: 29, name: "Tabac N' Coke", brand: "Fragrance World", category: "unisex",
    price: 20000, originalPrice: null,
    notes: ["Tobacco", "Vanilla", "Amber", "Musk"],
    descEn: "A bold, audacious gourmand. Opens with photorealistic Coca-Cola and lime, transitions into tobacco absolute and forget-me-not, closing on a rich benzoin, vanilla and amber base.",
    descFr: "Un gourmand audacieux. S'ouvre sur un Coca-Cola photoréaliste et citron vert, vers tabac absolu et myosotis, se fermant sur benjoin riche, vanille et ambre.",
    size: "100ml EDP", rating: 4.6, reviews: 44, badge: "New",
    hue: "#1A0A00", accent: "#884400",
    image: "/Tabac.png",
  },
];

export function getWhatsAppLink(perfumeName, size) {
  const msg = encodeURIComponent(`Hello W&S Fragrances! 👋\n\nI'd like to order:\n*${perfumeName}* (${size})\n\nPlease confirm availability and delivery. Thank you!`);
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`;
}